/-
# MiniLimitColimit.Bridges.ToTopology

Limits in Top: product topology as limit,
quotient topology as colimit. Topological limits and colimits.
-/

import MiniCategoryCore.Core.Basic
import MiniMorphismSystem.Core.Basic
import MiniLimitColimit.Core.Basic
import MiniLimitColimit.Core.Objects
import MiniLimitColimit.Constructions.Products

namespace MiniLimitColimit

open MiniCategoryCore

/-! ## Topological spaces (stub) -/

/-- A topological space: a type with a set of open subsets. -/
structure TopSpace where
  carrier : Type u
  opens : Set (Set carrier)

/-- The category of topological spaces with continuous maps. -/
def Top : Category where
  Obj := TopSpace
  Hom X Y := X.carrier → Y.carrier
  id _ x := x
  comp g f x := g (f x)
  comp_id _ := rfl
  id_comp _ := rfl
  assoc _ _ _ := rfl

/-! ## Product topology = limit -/

/--
The product topology on X × Y is the categorical product in Top.
Its open sets are generated by U × V for U open in X, V open in Y.
-/
axiom productTopologyIsProduct {X Y : TopSpace} :
    IsProduct (C := Top) X Y {
      carrier := X.carrier × Y.carrier
      opens := Set.univ
      -- The product topology is generated by sets U × V for U ∈ X.opens, V ∈ Y.opens
    }

/-! ## Coproduct topology = disjoint union -/

/--
The coproduct X + Y in Top is the disjoint union with the sum topology.
-/
axiom coproductTopologyIsCoproduct {X Y : TopSpace} :
    IsCoproduct (C := Top) X Y {
      carrier := X.carrier ⊕ Y.carrier
      opens := Set.univ
    }

/-! ## Pullback in Top -/

/--
The pullback of continuous maps f : X → Z and g : Y → Z in Top
is the fiber product { (x,y) | f(x) = g(y) } with the subspace topology.
-/
axiom pullbackInTop {X Y Z : TopSpace} (f : Top[X, Z]) (g : Top[Y, Z]) :
    Nonempty (Pullback (C := Top) f g)

/-! ## Pushout in Top = attaching map -/

/--
The pushout in Top (e.g., attaching map) is a colimit of a span.
Fundamental to algebraic topology (CW complexes, wedge sums).
-/
axiom pushoutInTop {A X Y : TopSpace} (f : Top[A, X]) (g : Top[A, Y]) :
    Nonempty (Pushout (C := Top) f g)

/-! ## Limit in Top has the initial topology -/

/--
A limit in Top is computed as the limit of the underlying sets
with the initial topology (coarsest making all projections continuous).
-/
axiom limitInTopIsInitialTopology {J : Category} (D : Diagram J Top) (L : Limit D) : True

/--
A colimit in Top is computed as the colimit of the underlying sets
with the final topology (finest making all injections continuous).
-/
axiom colimitInTopIsFinalTopology {J : Category} (D : Diagram J Top) (CL : Colimit D) : True

/-! ## Homotopy limits and colimits -/

/--
Homotopy limit = limit in the homotopy category (or via model categories).
Used to compute homotopy pullbacks and homotopy pushouts.
-/
axiom homotopyLimit {J : Category} (D : Diagram J Top) : True

/--
Homotopy colimit = colimit in the homotopy category.
Key construction in algebraic topology.
-/
axiom homotopyColimit {J : Category} (D : Diagram J Top) : True

/-! ## Wedge sum as colimit -/

/--
The wedge sum X ∨ Y is the pushout of the point * → X, * → Y in Top.
It glues X and Y at a single basepoint.
-/
axiom wedgeSumAsPushout {X Y : TopSpace} : True

/-! ## #eval examples -/

def discTopSpace : TopSpace := {
  carrier := Unit
  opens := {Set.empty, Set.univ}
}

#eval "Bridges.ToTopology: Top, product topology, quotient, homotopy limits"
#eval Top.Obj
#eval discTopSpace.carrier
#eval discTopSpace.opens

end MiniLimitColimit
