/-
# MiniLimitColimit.Constructions.Quotients

Coequalizer as colimit, initial as colimit of empty diagram,
pushout as colimit. Quotient objects via colimits.
-/

import MiniCategoryCore.Core.Basic
import MiniCategoryCore.Constructions.Universal
import MiniMorphismSystem.Core.Basic
import MiniMorphismSystem.Core.Objects
import MiniLimitColimit.Core.Basic
import MiniLimitColimit.Core.Objects
import MiniLimitColimit.Core.Laws

namespace MiniLimitColimit

open MiniCategoryCore
open MiniMorphismSystem

/-! ## Coequalizer as colimit of a parallel pair -/

/-- A cofork for parallel arrows f, g : A → B is an object Q with q : B → Q such that q ∘ f = q ∘ g. -/
structure Cofork {C : Category} {A B : C.Obj} (f g : C[A, B]) where
  obj : C.Obj
  coforkMap : C[B, obj]
  condition : C.comp coforkMap f = C.comp coforkMap g

/-- A coequalizer is a universal cofork. -/
structure Coequalizer {C : Category} {A B : C.Obj} (f g : C[A, B]) where
  cofork : Cofork f g
  mediate : ∀ (c : Cofork f g), C[cofork.obj, c.obj]
  factor : ∀ (c : Cofork f g), C.comp (mediate c) cofork.coforkMap = c.coforkMap
  unique : ∀ (c : Cofork f g) (h : C[cofork.obj, c.obj]),
    C.comp h cofork.coforkMap = c.coforkMap → h = mediate c

/-! ## Coequalizer in SetCat -/

def coequalizerInSet {A B : Type u} (f g : A → B) : Coequalizer (SetCat := SetCat) f g where
  cofork := {
    obj := Quot (fun b₁ b₂ => ∃ a, f a = b₁ ∧ g a = b₂)
    coforkMap b := Quot.mk _ b
    condition := by
      funext a
      apply Quot.sound
      exact ⟨a, rfl, rfl⟩
  }
  mediate c h := Quot.lift c.coforkMap (by
    intro b₁ b₂ h_eq
    rcases h_eq with ⟨a, hf, hg⟩
    have h_cond := congrFun c.condition a
    calc
      c.coforkMap b₁ = c.coforkMap (f a) := by rw [hf]
      _ = c.coforkMap (g a) := by simpa
      _ = c.coforkMap b₂ := by rw [hg]
  )
  factor c h := rfl
  unique c h h_eq := by
    funext x
    apply Quot.inductionOn x
    intro b
    have hx := congrFun h_eq b
    exact hx

/-! ## Initial as colimit of empty diagram -/

/--
The empty diagram gives the initial object as its colimit.
-/
axiom initialAsEmptyColimit (C : Category) (I : Initial C) :
    Colimit (Functor.const (DiscCat PEmpty) C I.obj)

/-! ## Pushout as colimit

The pushout is the colimit of a span diagram A ← X → B.
-/
structure PushoutCocone {C : Category} {A B X : C.Obj} (f : C[X, A]) (g : C[X, B]) where
  nadir : C.Obj
  u : C[A, nadir]
  v : C[B, nadir]
  commutes : C.comp u f = C.comp v g

structure Pushout {C : Category} {A B X : C.Obj} (f : C[X, A]) (g : C[X, B]) where
  cocone : PushoutCocone f g
  mediate : ∀ (c : PushoutCocone f g), C[cocone.nadir, c.nadir]
  factor_u : ∀ (c : PushoutCocone f g), C.comp (mediate c) cocone.u = c.u
  factor_v : ∀ (c : PushoutCocone f g), C.comp (mediate c) cocone.v = c.v
  unique : ∀ (c : PushoutCocone f g) (h : C[cocone.nadir, c.nadir]),
    C.comp h cocone.u = c.u → C.comp h cocone.v = c.v → h = mediate c

/-! ## Pushout in SetCat -/

/--
In SetCat, the pushout of X → A, X → B is the disjoint union A ⊕ B
quotiented by the relation f(x) ∼ g(x) for all x ∈ X.
-/
axiom pushoutInSet {A B X : Type u} (f : X → A) (g : X → B) :
    Pushout (SetCat := SetCat) f g

/-! ## Simplified: pushout of two sets as quotient of their sum -/

/--
The pushout object is given by (A ⊕ B) / ~ where ~ is generated by f(x) ~ g(x).
-/
def pushoutObjInSet {A B X : Type u} (f : X → A) (g : X → B) : Type u :=
  Quot (fun (s₁ s₂ : A ⊕ B) =>
    match s₁, s₂ with
    | Sum.inl a₁, Sum.inl a₂ => a₁ = a₂
    | Sum.inr b₁, Sum.inr b₂ => b₁ = b₂
    | Sum.inl a, Sum.inr b => ∃ x, f x = a ∧ g x = b
    | Sum.inr b, Sum.inl a => ∃ x, f x = a ∧ g x = b)

/-! ## #eval examples -/

def idNat : Nat → Nat := fun n => n
def addOne : Nat → Nat := fun n => n + 1

def cfork : Cofork (SetCat := SetCat) idNat addOne where
  obj := Nat
  coforkMap := fun n => n
  condition := by
    funext n; simp

def coequalizerId : Coequalizer (SetCat := SetCat)
    (fun (n : Nat) => n) (fun (n : Nat) => n) :=
  coequalizerInSet (fun (n : Nat) => n) (fun (n : Nat) => n)

#eval "Constructions.Quotients: Coequalizer, Pushout, Initial as colimit"
#eval cfork.coforkMap 5
#eval coequalizerId.cofork.obj
#eval pushoutObjInSet (fun (x : Nat) => x) (fun (x : Nat) => x)

end MiniLimitColimit
