import MiniCategoryCore

open MiniCategoryCore

-- #check all definitions from all modules
#check Category
#check SetCat
#check Category.op
#check Category.prod
#check DiscCat
#check CodiscCat
#check isSmall
#check Iso
#check IsIso
#check iso_refl
#check iso_symm
#check iso_trans
#check associativityLaw
#check leftIdentityLaw
#check rightIdentityLaw
#check categoryLaws
#check preservesId
#check preservesComp
#check naturalitySquare
#check Mono
#check Epi
#check SplitMono
#check SplitEpi
#check isIso_iff_split_mono_epi
#check Functor
#check Equivalence
#check isEquivalence
#check isSkeletal
#check isConnected
#check ProductCone
#check isProduct
#check HasBinaryProducts
#check Subobject
#check CatCongruence
#check QuotientCat
#check Initial
#check Terminal
#check Zero
#check Adjunction
#check PreorderCat
#check MonoidCat
#check GroupCat
#check CartesianClosed
#check ManifoldCat
#check SchemeCat
#check TopCategory
#check FundamentalGroupoid
#check Monad
